// 把命令都整理出来
export { apiRequest } from './apiRequest';
export { callCurrentFunc } from './callCurrentFunc';
export { callCustomPageFunc } from './callCustomPageFunc';
export { callParentCustomFunc } from './callParentCustomFunc';
export { callSelfFunc } from './callSelfFunc';
export { clearTimer } from './clearTimer';
export { clearValue } from './clearValue';
export { closeModal } from './closeModal';
export { getConsole as console } from './console';
export { customActionCode } from './customActionCode';
export { getDefault as defaultCmd } from './defaultCmd';
export { downloadByFileId } from './downloadByFileId';
export { dropPageByCatch } from './dropPageByCatch';
export { exportBusiObjectData } from './exportBusiObjectData';
export { exportCustomBusiObjectData } from './exportCustomBusiObjectData';
export { exportCustomData } from './exportCustomData';
export { exportSQLServiceData } from './exportSQLServiceData';
export { getValue } from './getValue';
export { hideMessage } from './hideMessage';
export { history } from './history';
export { historyGoBack } from './historyGoBack';
export { historyReplace } from './historyReplace';
export { getIfelse as ifelse } from './ifelse';
export { importCustomBusiObjectData } from './importCustomBusiObjectData';
export { okCallbackData } from './okCallbackData';
export { postObjectData } from './postObjectData';
export { previewFile } from './previewFile';
export { reloadDataSource } from './reloadDataSource';
export { getResetDataSource as resetDataSource } from './resetDataSource';
export { returnCmd as return } from './return';
export { saveBlobFile } from './saveBlobFile';
export { getSetDataSource as setDataSource } from './setDataSource';
export { setDownloadResponse } from './setDownloadResponse';
export { setInterval } from './setInterval';
export { setLoading } from './setLoading';
export { setPageSrc } from './setPageSrc';
export { setSrc } from './setSrc';
export { setTimeout } from './setTimeout';
export { setTimer } from './setTimer';
export { showAppCustomModal } from './showAppCustomModal';
export { showCustomModal } from './showCustomModal';
export { showMessage } from './showMessage';
export { showModal } from './showModal';
export { sysSetDisable } from './sysSetDisable';
export { sysSetRequired } from './sysSetRequired';
export { sysSetValue } from './sysSetValue';
export { sysSetVisible } from './sysSetVisible';
