export const REACT_CHUNK_NAME = {
  RenderStart: 'ReactComponentRenderStart',
  RenderPre: 'ReactComponentRenderPre',
  RenderEnd: 'ReactComponentRenderEnd',
  RenderJSX: 'ReactComponentRenderJSX',
  DidMountStart: 'ReactComponentDidMountStart',
  DidMountEnd: 'ReactComponentDidMountEnd',
  DidMountContent: 'ReactComponentDidMountContent',
  DidUpdateStart: 'ReactComponentDidUpdateStart',
  DidUpdateEnd: 'ReactComponentDidUpdateEnd',
  DidUpdateContent: 'ReactComponentDidUpdateContent',
  WillUnmountStart: 'ReactComponentWillUnmountStart',
  WillUnmountEnd: 'ReactComponentWillUnmountEnd',
  WillUnmountContent: 'ReactComponentWillUnmountContent',
};
