// 把命令都整理出来
export { apiRequest } from './apiRequest';
export { callCurrentFunc } from './callCurrentFunc';
export { callCustomPageFunc } from './callCustomPageFunc';
export { callParentCustomFunc } from './callParentCustomFunc';
export { callSelfFunc } from './callSelfFunc';
export { changeContent } from './changeContent';
export { clearOptions } from './clearOptions';
export { clearValue } from './clearValue';
export { closeModal } from './closeModal';
export { getConsole as console } from './console';
export { customActionCode } from './customActionCode';
export { getDefault as defaultCmd } from './defaultCmd';
export { dropPageByCatch } from './dropPageByCatch';
export { exportSQLServiceData } from './exportSQLServiceData';
export { getCurrentFormValues } from './getCurrentFormValues';
export { getFormValue } from './getFormValue';
export { getValue } from './getValue';
export { hideMessage } from './hideMessage';
export { history } from './history';
export { historyGoBack } from './historyGoBack';
export { getIfelse as ifelse } from './ifelse';
export { okCallbackData } from './okCallbackData';
export { previewFile } from './previewFile';
export { reloadDataSource } from './reloadDataSource';
export { reloadSelectData } from './reloadSelectData';
export { getResetCurrentForm as resetCurrentForm } from './resetCurrentForm';
export { getResetDataSource as resetDataSource } from './resetDataSource';
export { resetForm } from './resetForm';
export { returnCmd as return } from './return';
export { setCompState } from './setCompState';
export { getSetDataSource as setDataSource } from './setDataSource';
export { setFormValues } from './setFormValues';
export { setLoading } from './setLoading';
export { setPageSrc } from './setPageSrc';
export { setTimer } from './setTimer';
export { showCustomModal } from './showCustomModal';
export { showMessage } from './showMessage';
export { sysSetDisable } from './sysSetDisable';
export { sysSetRequired } from './sysSetRequired';
export { sysSetValue } from './sysSetValue';
export { sysSetVisible } from './sysSetVisible';
export { validateCurrentForm } from './validateCurrentForm';
export { validateForm } from './validateForm';
export { validateAllForm } from './validateAllForm';
export { getAllFormValues } from './getAllFormValues';
export { resetAllForm } from './resetAllForm';
export { setCurrentFormValues } from './setCurrentFormValues';
export { setTimeout } from './setTimeout';
export { clearTimer } from './clearTimer';
export { setInterval } from './setInterval';


