export const functorsKeys = [
  'ABS',
  'AES_DECRYPT',
  'AES_ENCRYPT',
  'ARRAYINDEX',
  'ARRAYTOSTR',
  'AVERAGE',
  'CONCAT',
  'COUNTA',
  'COUNTARRAY',
  'COUNTBLANK',
  'COUNTCHAR',
  'DATAMASK',
  'DATEADD',
  'DATENOW',
  'DATETIME',
  'IF',
  'INT',
  'LOG',
  'MAX',
  'MIN',
  'MOD',
  'NUMBER',
  'OBJECTVALUE',
  'POWER',
  'PRODUCT',
  'RANDBETWEEN',
  'RANDOMNUM',
  'ROUND',
  'ROUNDDOWN',
  'ROUNDUP',
  'STRTOARRAY',
  'SUM',
];

export const functorTopKey = 'functorsMap';
export const excludeCalleeNames = ['classNames', functorTopKey];
