// 注意: 出码模块正在调试
import React from 'react';
// 默认都加，应该用到再加

import { Description } from '@/components/factory';

import { useEffect } from 'react';

import { PageProps, withPageHOC } from '@/utils/withPageHOC';

const BusiComp734913$$BusiComp: React.FC<PageProps> = ({
  data,
  CMDGenerator,
  attrDataMap = {},
  customActionMapRef,
  injectData,
  refs,
  state,
  functorsMap,
  getStaticDataSourceService,
  getValue,
  componentItem,
  style,
  urlParam,
}) => {
  useEffect(() => {
    return () => {};
  }, []);

  useEffect(() => {
    const eventDatacustomActionCode2: any = [
      {
        type: 'customActionCode',
        dataId: 170530142393976930,
        options: {
          compId: 'customActionCode',
          compName: 'page',
          id: '819775',
          pageJsonId: '734913',
          code: 'function main(data,state,success,fail){data.singleGroup=state.singleGroup;success()};',
        },
        line_number: 1,
        callback1: [
          {
            type: 'setDataSource',
            dataId: 170530144379315620,
            options: {
              compId: 'setDataSource',
              compName: 'page',
              id: '966101',
              pageJsonId: '734913',
              dataSourceId: 170530122519373800,
              dataSourceName: 'singleGroup',
              dataSourceRelType: 'custom',
              dataSourceSetValue: [
                {
                  code: 'groupId',
                  name: '集团编码',
                  type: 'string',
                  attrId: '9972756',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'groupName',
                  name: '集团名称',
                  type: 'string',
                  attrId: '378188',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'groupCreditRate',
                  name: '集团征信等级',
                  type: 'string',
                  attrId: '596172',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'belongCityText',
                  name: '归属地市',
                  type: 'string',
                  attrId: '963427',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'belongAreaText',
                  name: '归属县市',
                  type: 'string',
                  attrId: '378853',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'customerType',
                  name: '客户类型',
                  type: 'string',
                  attrId: '2082955',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'institutionType',
                  name: '机构类型',
                  type: 'string',
                  attrId: '622457',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'industryCategory',
                  name: '行业大类',
                  type: 'string',
                  attrId: '5903271',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'industrySubCategory',
                  name: '行业小类',
                  type: 'string',
                  attrId: '910156',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'custManagerName',
                  name: '客户经理姓名',
                  type: 'string',
                  attrId: '512547',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'custManagerPhone',
                  name: '客户经理联系电话',
                  type: 'string',
                  attrId: '5891102',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'custManagerCreditRate',
                  name: '客户经理征信等级',
                  type: 'string',
                  attrId: '339061',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'earliestOverdueTime',
                  name: '最早欠费时间',
                  type: 'string',
                  attrId: '173842',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'totalArrearage',
                  name: '累计欠费（元）',
                  type: 'string',
                  attrId: '3436255',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'appliedWhiteListNum',
                  name: '已申请白名单次数（次）',
                  type: 'string',
                  attrId: '091986',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'maxOverdueMonth',
                  name: '最大逾期月数（月）',
                  type: 'string',
                  attrId: '466333',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'cumulativeOverdueFee',
                  name: '累计逾期欠费（元）',
                  type: 'string',
                  attrId: '8424529',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'appliedWhiteListDay',
                  name: '已申请白名单天数（天）',
                  type: 'string',
                  attrId: '6182514',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'maxArrearageBillItem',
                  name: '最大欠费账目项',
                  type: 'string',
                  attrId: '010049',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'maxArrearageBillItemFee',
                  name: '最大欠费账目项欠费（元）',
                  type: 'string',
                  attrId: '24926',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'lastCollectionRequireYear',
                  name: '最近一次催缴要求（近一年）',
                  type: 'string',
                  attrId: '695473',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'lastCollectionTimeYear',
                  name: '最近一次催缴时间（近一年）',
                  type: 'string',
                  attrId: '813042',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  code: 'lastCollectionActionYear',
                  name: '最近一次催缴动作（近一年）',
                  type: 'string',
                  attrId: '613345',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                },
                {
                  attrId: '0720664',
                  code: 'param0',
                  name: '无用属性',
                  type: 'string',
                  initialData: { type: 'static' },
                  showInput: true,
                },
              ],
              operateType: 1,
              onlySetPatch: true,
              otherObjectArrayOptions: {},
              targetDataSourcePaths: [],
            },
            line_number: 2,
            callback1: [],
            callback2: [],
          },
        ],
        callback2: [],
      },
    ];
    eventDatacustomActionCode2.params = [] || [];
    CMDGenerator(eventDatacustomActionCode2, {}, 'customActionCode', {
      id: 'customActionCode',
      name: 'customActionCode',
      type: 'customActionCode',
      platform: 'undefined',
    });
  });

  return (
    <div
      style={{ height: '100%', ...style }}
      className="__CustomClass_734913__"
    >
      <Description
        name={'描述列表'}
        columns={[
          {
            title: '集团编码',
            key: 'groupId',
            dataIndex: 'groupId',
            label: '集团编码',
            id: '025606',
            customRendering: undefined,
          },
          {
            title: '集团名称',
            key: 'groupName',
            dataIndex: 'groupName',
            label: '集团名称',
            id: '1232471',
            customRendering: undefined,
          },
          {
            title: '集团征信等级',
            key: 'groupCreditRate',
            dataIndex: 'groupCreditRate',
            label: '集团征信等级',
            id: '067304',
            customRendering: undefined,
          },
          {
            title: '归属地市',
            key: 'belongCityText',
            dataIndex: 'belongCityText',
            label: '归属地市',
            id: '37141',
            customRendering: undefined,
          },
          {
            title: '归属县市',
            key: 'belongAreaText',
            dataIndex: 'belongAreaText',
            label: '归属县市',
            id: '318851',
            customRendering: undefined,
          },
          {
            title: '客户类型',
            key: 'customerType',
            dataIndex: 'customerType',
            label: '客户类型',
            id: '638174',
            customRendering: undefined,
          },
          {
            title: '机构类型',
            key: 'institutionType',
            dataIndex: 'institutionType',
            label: '机构类型',
            id: '7950114',
            customRendering: undefined,
          },
          {
            title: '行业大类',
            key: 'industryCategory',
            dataIndex: 'industryCategory',
            label: '行业大类',
            id: '0261009',
            customRendering: undefined,
          },
          {
            title: '行业小类',
            key: 'industrySubCategory',
            dataIndex: 'industrySubCategory',
            label: '行业小类',
            id: '03671457',
            customRendering: undefined,
          },
          {
            title: '客户经理姓名',
            key: 'custManagerName',
            dataIndex: 'custManagerName',
            label: '客户经理姓名',
            id: '34518',
            customRendering: undefined,
          },
          {
            title: '客户经理联系电话',
            key: 'custManagerPhone',
            dataIndex: 'custManagerPhone',
            label: '客户经理联系电话',
            id: '150186',
            customRendering: undefined,
          },
          {
            title: '客户经理征信等级',
            key: 'custManagerCreditRate',
            dataIndex: 'custManagerCreditRate',
            label: '客户经理征信等级',
            id: '9813577',
            customRendering: undefined,
          },
          {
            title: '最早欠费时间',
            key: 'earliestOverdueTime',
            dataIndex: 'earliestOverdueTime',
            label: '最早欠费时间',
            id: '685549',
            customRendering: undefined,
          },
          {
            title: '累计欠费（元）',
            key: 'totalArrearage',
            dataIndex: 'totalArrearage',
            label: '累计欠费（元）',
            id: '2058',
            customRendering: undefined,
          },
          {
            title: '已申请白名单次数（次）',
            key: 'appliedWhiteListNum',
            dataIndex: 'appliedWhiteListNum',
            label: '已申请白名单次数（次）',
            id: '863466',
            customRendering: undefined,
          },
          {
            title: '最大逾期月数（月）',
            key: 'maxOverdueMonth',
            dataIndex: 'maxOverdueMonth',
            label: '最大逾期月数（月）',
            id: '4390072',
            customRendering: undefined,
          },
          {
            title: '累计逾期欠费（元）',
            key: 'cumulativeOverdueFee',
            dataIndex: 'cumulativeOverdueFee',
            label: '累计逾期欠费（元）',
            id: '755499',
            customRendering: undefined,
          },
          {
            title: '已申请白名单天数（天）',
            key: 'appliedWhiteListDay',
            dataIndex: 'appliedWhiteListDay',
            label: '已申请白名单天数（天）',
            id: '662355',
            customRendering: undefined,
          },
          {
            title: '最大欠费账目项',
            key: 'maxArrearageBillItem',
            dataIndex: 'maxArrearageBillItem',
            label: '最大欠费账目项',
            id: '739631',
            customRendering: undefined,
          },
          {
            title: '最大欠费账目项欠费（元）',
            key: 'maxArrearageBillItemFee',
            dataIndex: 'maxArrearageBillItemFee',
            label: '最大欠费账目项欠费（元）',
            id: '030747',
            customRendering: undefined,
          },
          {
            title: '无用属性',
            key: 'param0',
            dataIndex: 'param0',
            label: ' ',
            id: '6052273',
            customRendering: undefined,
          },
          {
            title: '最近一次催缴要求（近一年）',
            key: 'lastCollectionRequireYear',
            dataIndex: 'lastCollectionRequireYear',
            label: '最近一次催缴要求（近一年）',
            id: '424248',
            customRendering: undefined,
          },
          {
            title: '最近一次催缴时间（近一年）',
            key: 'lastCollectionTimeYear',
            dataIndex: 'lastCollectionTimeYear',
            label: '最近一次催缴时间（近一年）',
            id: '0697758',
            customRendering: undefined,
          },
          {
            title: '最近一次催缴动作（近一年）',
            key: 'lastCollectionActionYear',
            dataIndex: 'lastCollectionActionYear',
            label: '最近一次催缴动作（近一年）',
            id: '1160852',
            customRendering: undefined,
          },
        ]}
        bordered={true}
        labelWidth={undefined}
        colSpan={8}
        colon={true}
        labelAlign={'left'}
        dataSource={data?.singleGroup}
        descColumns={[
          {
            title: '集团编码',
            key: 'groupId',
            dataIndex: 'groupId',
            label: '集团编码',
            id: '025606',
          },
          {
            title: '集团名称',
            key: 'groupName',
            dataIndex: 'groupName',
            label: '集团名称',
            id: '1232471',
          },
          {
            title: '集团征信等级',
            key: 'groupCreditRate',
            dataIndex: 'groupCreditRate',
            label: '集团征信等级',
            id: '067304',
          },
          {
            title: '归属地市',
            key: 'belongCityText',
            dataIndex: 'belongCityText',
            label: '归属地市',
            id: '37141',
          },
          {
            title: '归属县市',
            key: 'belongAreaText',
            dataIndex: 'belongAreaText',
            label: '归属县市',
            id: '318851',
          },
          {
            title: '客户类型',
            key: 'customerType',
            dataIndex: 'customerType',
            label: '客户类型',
            id: '638174',
          },
          {
            title: '机构类型',
            key: 'institutionType',
            dataIndex: 'institutionType',
            label: '机构类型',
            id: '7950114',
          },
          {
            title: '行业大类',
            key: 'industryCategory',
            dataIndex: 'industryCategory',
            label: '行业大类',
            id: '0261009',
          },
          {
            title: '行业小类',
            key: 'industrySubCategory',
            dataIndex: 'industrySubCategory',
            label: '行业小类',
            id: '03671457',
          },
          {
            title: '客户经理姓名',
            key: 'custManagerName',
            dataIndex: 'custManagerName',
            label: '客户经理姓名',
            id: '34518',
          },
          {
            title: '客户经理联系电话',
            key: 'custManagerPhone',
            dataIndex: 'custManagerPhone',
            label: '客户经理联系电话',
            id: '150186',
          },
          {
            title: '客户经理征信等级',
            key: 'custManagerCreditRate',
            dataIndex: 'custManagerCreditRate',
            label: '客户经理征信等级',
            id: '9813577',
          },
          {
            title: '最早欠费时间',
            key: 'earliestOverdueTime',
            dataIndex: 'earliestOverdueTime',
            label: '最早欠费时间',
            id: '685549',
          },
          {
            title: '累计欠费（元）',
            key: 'totalArrearage',
            dataIndex: 'totalArrearage',
            label: '累计欠费（元）',
            id: '2058',
          },
          {
            title: '已申请白名单次数（次）',
            key: 'appliedWhiteListNum',
            dataIndex: 'appliedWhiteListNum',
            label: '已申请白名单次数（次）',
            id: '863466',
          },
          {
            title: '最大逾期月数（月）',
            key: 'maxOverdueMonth',
            dataIndex: 'maxOverdueMonth',
            label: '最大逾期月数（月）',
            id: '4390072',
          },
          {
            title: '累计逾期欠费（元）',
            key: 'cumulativeOverdueFee',
            dataIndex: 'cumulativeOverdueFee',
            label: '累计逾期欠费（元）',
            id: '755499',
          },
          {
            title: '已申请白名单天数（天）',
            key: 'appliedWhiteListDay',
            dataIndex: 'appliedWhiteListDay',
            label: '已申请白名单天数（天）',
            id: '662355',
          },
          {
            title: '最大欠费账目项',
            key: 'maxArrearageBillItem',
            dataIndex: 'maxArrearageBillItem',
            label: '最大欠费账目项',
            id: '739631',
          },
          {
            title: '最大欠费账目项欠费（元）',
            key: 'maxArrearageBillItemFee',
            dataIndex: 'maxArrearageBillItemFee',
            label: '最大欠费账目项欠费（元）',
            id: '030747',
          },
          {
            title: '无用属性',
            key: 'param0',
            dataIndex: 'param0',
            label: ' ',
            id: '6052273',
          },
          {
            title: '最近一次催缴要求（近一年）',
            key: 'lastCollectionRequireYear',
            dataIndex: 'lastCollectionRequireYear',
            label: '最近一次催缴要求（近一年）',
            id: '424248',
          },
          {
            title: '最近一次催缴时间（近一年）',
            key: 'lastCollectionTimeYear',
            dataIndex: 'lastCollectionTimeYear',
            label: '最近一次催缴时间（近一年）',
            id: '0697758',
          },
          {
            title: '最近一次催缴动作（近一年）',
            key: 'lastCollectionActionYear',
            dataIndex: 'lastCollectionActionYear',
            label: '最近一次催缴动作（近一年）',
            id: '1160852',
          },
        ]}
        labelSize={'200px'}
        $$componentItem={{
          id: 'Description_46427466',
          uid: 'Description_46427466',
          type: 'Description',
          ...componentItem,
        }}
        disabled={false}
        visible={true}
        readOnly={false}
        ref={(r: any) => (refs['Description_46427466'] = r)}
        {...injectData}
      />
    </div>
  );
};

export default withPageHOC(BusiComp734913$$BusiComp, {
  pageId: 'pageId 未找到',
  hasLogin: true,
  defaultState: { singleGroup: '' },
});
