// 注意: 出码模块正在调试
import React from 'react';
// 默认都加，应该用到再加
import Popover from '@/components/Popover';

import { Description } from '@/components/factory';

import { useEffect } from 'react';

import { PageProps, withPageHOC } from '@/utils/withPageHOC';

import dataSource from './dataSource.json';

const pageId = '1061968734141374464';
const BusiComp963983$$BusiComp: React.FC<PageProps> = ({
  data,
  CMDGenerator,
  attrDataMap = {},
  customActionMapRef,
  injectData,
  refs,
  state,
  functorsMap,
  getStaticDataSourceService,
  getValue,
  componentItem,
  style,
  urlParam,
  parentEngineId = pageId,
}) => {
  useEffect(() => {
    return () => {};
  }, []);

  useEffect(() => {
    const eventDatacustomActionCode3: any = [
      {
        type: 'customActionCode',
        dataId: 170480003267299780,
        options: {
          compId: 'customActionCode',
          compName: 'page',
          id: '298891',
          pageJsonId: '963983',
          code: 'function main(data,state,success,fail){console.log("\\u96C6\\u56E2\\u4E1A\\u52A1\\u7EC4\\u4EF6\\u5165\\u53C2\\uFF1A",state.groupInfo);data.groupInfo=state.groupInfo;success()};',
          actionTitle: '对groupInfo数据源赋值',
        },
        line_number: 1,
        callback1: [
          {
            type: 'setDataSource',
            dataId: 170480004904012200,
            options: {
              compId: 'setDataSource',
              compName: 'page',
              id: '877759',
              pageJsonId: '963983',
              dataSourceId: 170479978055553180,
              dataSourceName: 'groupInfo',
              dataSourceRelType: 'custom',
              dataSourceSetValue: [
                {
                  code: 'groupId',
                  name: '集团编码',
                  type: 'string',
                  attrId: '9271516',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['groupId'],
                  _idpath: ['9271516'],
                },
                {
                  code: 'groupName',
                  name: '集团名称',
                  type: 'string',
                  attrId: '726678',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['groupName'],
                  _idpath: ['726678'],
                },
                {
                  code: 'groupLevelName',
                  name: '价值等级',
                  type: 'string',
                  attrId: '935688',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['groupLevelName'],
                  _idpath: ['935688'],
                },
                {
                  code: 'paidNum',
                  name: '付费号码',
                  type: 'string',
                  attrId: '303711',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['paidNum'],
                  _idpath: ['303711'],
                },
                {
                  code: 'belongCityText',
                  name: '归属地市',
                  type: 'string',
                  attrId: '338152',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['belongCityText'],
                  _idpath: ['338152'],
                },
                {
                  code: 'belongAreaText',
                  name: '归属区县',
                  type: 'string',
                  attrId: '09001',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['belongAreaText'],
                  _idpath: ['09001'],
                },
                {
                  code: 'isAgencyGroup',
                  name: '是否代理商集团',
                  type: 'string',
                  attrId: '0873426',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['isAgencyGroup'],
                  _idpath: ['0873426'],
                },
                {
                  code: 'groupCreditRate',
                  name: '集团征信等级',
                  type: 'string',
                  attrId: '103446',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['groupCreditRate'],
                  _idpath: ['103446'],
                },
                {
                  code: 'institutionType',
                  name: '机构类型',
                  type: 'string',
                  attrId: '7088516',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['institutionType'],
                  _idpath: ['7088516'],
                },
                {
                  code: 'industryCategory',
                  name: '行业大类',
                  type: 'string',
                  attrId: '814387',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['industryCategory'],
                  _idpath: ['814387'],
                },
                {
                  code: 'customerType',
                  name: '客户类型',
                  type: 'string',
                  attrId: '833595',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['customerType'],
                  _idpath: ['833595'],
                },
                {
                  code: 'custManager',
                  name: '客户经理',
                  type: 'string',
                  attrId: '821807',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['custManager'],
                  _idpath: ['821807'],
                },
                {
                  code: 'custManagerPhone',
                  name: '客户经理联系电话',
                  type: 'string',
                  attrId: '2108154',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['custManagerPhone'],
                  _idpath: ['2108154'],
                },
                {
                  code: 'custManagerCreditRate',
                  name: '客户经理征信等级',
                  type: 'string',
                  attrId: '0908863',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['custManagerCreditRate'],
                  _idpath: ['0908863'],
                },
                {
                  code: 'appliedRedListNum',
                  name: '已申请红名单数（个）',
                  type: 'string',
                  attrId: '886012',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['appliedRedListNum'],
                  _idpath: ['886012'],
                },
                {
                  code: 'redControlNum',
                  name: '红名管控上线数（个）',
                  type: 'string',
                  attrId: '28103',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['redControlNum'],
                  _idpath: ['28103'],
                },
                {
                  code: 'appliedRedListNumYear',
                  name: '当年红名单已申请次数（次）',
                  type: 'string',
                  attrId: '142299',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['appliedRedListNumYear'],
                  _idpath: ['142299'],
                },
                {
                  code: 'groupEarliestOverdueTime',
                  name: '集团最早欠费时间',
                  type: 'string',
                  attrId: '501543',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['groupEarliestOverdueTime'],
                  _idpath: ['501543'],
                },
                {
                  code: 'groupTotalOverdueFee',
                  name: '集团总欠费（元）',
                  type: 'string',
                  attrId: '9159755',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['groupTotalOverdueFee'],
                  _idpath: ['9159755'],
                },
                {
                  code: 'appliedWhiteListNum',
                  name: '已申请白名单次数（次）',
                  type: 'string',
                  attrId: '112978',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['appliedWhiteListNum'],
                  _idpath: ['112978'],
                },
                {
                  code: 'maxOverdueMonth',
                  name: '最大逾期月数 （月）',
                  type: 'string',
                  attrId: '708173',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['maxOverdueMonth'],
                  _idpath: ['708173'],
                },
                {
                  code: 'groupCumulativeOverdueFee',
                  name: '集团累计逾期（元）',
                  type: 'string',
                  attrId: '1230214',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['groupCumulativeOverdueFee'],
                  _idpath: ['1230214'],
                },
                {
                  code: 'appliedWhiteListDay',
                  name: '已申请白名单天数（天）',
                  type: 'string',
                  attrId: '218654',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['appliedWhiteListDay'],
                  _idpath: ['218654'],
                },
                {
                  code: 'lastCollectionRequireYear',
                  name: '最近一次催缴要求（近一年）',
                  type: 'string',
                  attrId: '645616',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['lastCollectionRequireYear'],
                  _idpath: ['645616'],
                },
                {
                  code: 'lastCollectionTimeYear',
                  name: '最近一次催缴时间（近一年）',
                  type: 'string',
                  attrId: '088962',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['lastCollectionTimeYear'],
                  _idpath: ['088962'],
                },
                {
                  code: 'lastCollectionActionYear',
                  name: '最近一次催缴动作（近一年）',
                  type: 'string',
                  attrId: '8449664',
                  initialData: { type: 'static', value: '' },
                  parentKey: '1',
                  parentType: 'object',
                  showInput: true,
                  _codePath: ['lastCollectionActionYear'],
                  _idpath: ['8449664'],
                },
                {
                  attrId: '1937433',
                  code: 'param0',
                  name: '属性',
                  type: 'string',
                  initialData: { type: 'static' },
                  showInput: true,
                  _codePath: ['param0'],
                  _idpath: ['1937433'],
                },
              ],
              operateType: 1,
              onlySetPatch: true,
              otherObjectArrayOptions: {},
              targetDataSourcePaths: [],
            },
            line_number: 2,
            callback1: [],
            callback2: [],
          },
        ],
        callback2: [],
      },
    ];
    eventDatacustomActionCode3.params = [] || [];
    CMDGenerator(eventDatacustomActionCode3, {}, 'customActionCode', {
      id: 'customActionCode',
      name: 'customActionCode',
      type: 'customActionCode',
      platform: 'undefined',
    });
  });

  return (
    <div
      style={{ height: '100%', ...style }}
      className="__CustomClass_963983__"
    >
      <Description
        name={'描述列表'}
        columns={[
          {
            title: '集团编码',
            key: 'groupId',
            dataIndex: 'groupId',
            label: '集团编码',
            id: '052594',
            customRendering: undefined,
          },
          {
            title: '集团名称',
            key: 'groupName',
            dataIndex: 'groupName',
            label: '集团名称',
            id: '414585',
            customRendering: undefined,
          },
          {
            title: '价值等级',
            key: 'groupLevelName',
            dataIndex: 'groupLevelName',
            label: '价值等级',
            id: '243139',
            customRendering: undefined,
          },
          {
            title: '付费号码',
            key: 'paidNum',
            dataIndex: 'paidNum',
            label: '付费号码',
            id: '373308',
            customRendering: undefined,
          },
          {
            title: '归属地市',
            key: 'belongCityText',
            dataIndex: 'belongCityText',
            label: '归属地市',
            id: '9616012',
            customRendering: undefined,
          },
          {
            title: '归属区县',
            key: 'belongAreaText',
            dataIndex: 'belongAreaText',
            label: '归属区县',
            id: '23736',
            customRendering: undefined,
          },
          {
            title: '是否代理商集团',
            key: 'isAgencyGroup',
            dataIndex: 'isAgencyGroup',
            label: '是否代理商集团',
            id: '1130319',
            customRendering: undefined,
          },
          {
            title: '集团征信等级',
            key: 'groupCreditRate',
            dataIndex: 'groupCreditRate',
            label: '集团征信等级',
            id: '173459',
            customRendering: undefined,
          },
          {
            title: '属性',
            key: 'param0',
            dataIndex: 'param0',
            label: ' ',
            id: '117789',
            customRendering: undefined,
          },
          {
            title: '机构类型',
            key: 'institutionType',
            dataIndex: 'institutionType',
            label: '机构类型',
            id: '920044',
            customRendering: undefined,
          },
          {
            title: '行业大类',
            key: 'industryCategory',
            dataIndex: 'industryCategory',
            label: '行业大类',
            id: '6104768',
            customRendering: undefined,
          },
          {
            title: '客户类型',
            key: 'customerType',
            dataIndex: 'customerType',
            label: '客户类型',
            id: '97562175',
            customRendering: undefined,
          },
          {
            title: '客户经理',
            key: 'custManager',
            dataIndex: 'custManager',
            label: '客户经理',
            id: '785903',
            customRendering: undefined,
          },
          {
            title: '客户经理联系电话',
            key: 'custManagerPhone',
            dataIndex: 'custManagerPhone',
            label: '客户经理联系电话',
            id: '77329844',
            customRendering: undefined,
          },
          {
            title: '客户经理征信等级',
            key: 'custManagerCreditRate',
            dataIndex: 'custManagerCreditRate',
            label: '客户经理征信等级',
            id: '3562793',
            customRendering: undefined,
          },
          {
            title: '已申请红名单数（个）',
            key: 'appliedRedListNum',
            dataIndex: 'appliedRedListNum',
            label: '已申请红名单数（个）',
            id: '0413365',
            customRendering: undefined,
          },
          {
            title: '红名管控上线数（个）',
            key: 'redControlNum',
            dataIndex: 'redControlNum',
            label: '红名管控上线数（个）',
            id: '137417',
            customRendering: undefined,
          },
          {
            title: '当年红名单已申请次数（次）',
            key: 'appliedRedListNumYear',
            dataIndex: 'appliedRedListNumYear',
            label: '当年红名单已申请次数（次）',
            id: '256653',
            customRendering: undefined,
          },
          {
            title: '集团最早欠费时间',
            key: 'groupEarliestOverdueTime',
            dataIndex: 'groupEarliestOverdueTime',
            label: '集团最早欠费时间',
            id: '872497',
            customRendering: undefined,
          },
          {
            title: '集团总欠费（元）',
            key: 'groupTotalOverdueFee',
            dataIndex: 'groupTotalOverdueFee',
            label: '集团总欠费（元）',
            id: '1918254',
            customRendering: undefined,
          },
          {
            title: '已申请白名单次数（次）',
            key: 'appliedWhiteListNum',
            dataIndex: 'appliedWhiteListNum',
            label: '已申请白名单次数（次）',
            id: '533072',
            customRendering: undefined,
          },
          {
            title: '最大逾期月数 （月）',
            key: 'maxOverdueMonth',
            dataIndex: 'maxOverdueMonth',
            label: '最大逾期月数 （月）',
            id: '40659',
            customRendering: undefined,
          },
          {
            title: '集团累计逾期（元）',
            key: 'groupCumulativeOverdueFee',
            dataIndex: 'groupCumulativeOverdueFee',
            label: '集团累计逾期（元）',
            id: '5515184',
            customRendering: undefined,
          },
          {
            title: '已申请白名单天数（天）',
            key: 'appliedWhiteListDay',
            dataIndex: 'appliedWhiteListDay',
            label: '已申请白名单天数（天）',
            id: '999316',
            customRendering: undefined,
          },
          {
            title: '最近一次催缴要求（近一年）',
            key: 'lastCollectionRequireYear',
            dataIndex: 'lastCollectionRequireYear',
            label: '最近一次催缴要求（近一年）',
            id: '578491',
            customRendering: undefined,
          },
          {
            title: '最近一次催缴时间（近一年）',
            key: 'lastCollectionTimeYear',
            dataIndex: 'lastCollectionTimeYear',
            label: '最近一次催缴时间（近一年）',
            id: '88838',
            customRendering: undefined,
          },
          {
            title: '最近一次催缴动作（近一年）',
            key: 'lastCollectionActionYear',
            dataIndex: 'lastCollectionActionYear',
            label: '最近一次催缴动作（近一年）',
            id: '3671033',
            customRendering: undefined,
          },
        ]}
        bordered={true}
        labelWidth={undefined}
        colSpan={8}
        colon={true}
        labelAlign={'left'}
        descColumns={[
          {
            title: '集团编码',
            key: 'groupId',
            dataIndex: 'groupId',
            label: '集团编码',
            id: '052594',
          },
          {
            title: '集团名称',
            key: 'groupName',
            dataIndex: 'groupName',
            label: '集团名称',
            id: '414585',
          },
          {
            title: '价值等级',
            key: 'groupLevelName',
            dataIndex: 'groupLevelName',
            label: '价值等级',
            id: '243139',
          },
          {
            title: '付费号码',
            key: 'paidNum',
            dataIndex: 'paidNum',
            label: '付费号码',
            id: '373308',
          },
          {
            title: '归属地市',
            key: 'belongCityText',
            dataIndex: 'belongCityText',
            label: '归属地市',
            id: '9616012',
          },
          {
            title: '归属区县',
            key: 'belongAreaText',
            dataIndex: 'belongAreaText',
            label: '归属区县',
            id: '23736',
          },
          {
            title: '是否代理商集团',
            key: 'isAgencyGroup',
            dataIndex: 'isAgencyGroup',
            label: '是否代理商集团',
            id: '1130319',
          },
          {
            title: '集团征信等级',
            key: 'groupCreditRate',
            dataIndex: 'groupCreditRate',
            label: '集团征信等级',
            id: '173459',
          },
          {
            title: '属性',
            key: 'param0',
            dataIndex: 'param0',
            label: ' ',
            id: '117789',
          },
          {
            title: '机构类型',
            key: 'institutionType',
            dataIndex: 'institutionType',
            label: '机构类型',
            id: '920044',
          },
          {
            title: '行业大类',
            key: 'industryCategory',
            dataIndex: 'industryCategory',
            label: '行业大类',
            id: '6104768',
          },
          {
            title: '客户类型',
            key: 'customerType',
            dataIndex: 'customerType',
            label: '客户类型',
            id: '97562175',
          },
          {
            title: '客户经理',
            key: 'custManager',
            dataIndex: 'custManager',
            label: '客户经理',
            id: '785903',
          },
          {
            title: '客户经理联系电话',
            key: 'custManagerPhone',
            dataIndex: 'custManagerPhone',
            label: '客户经理联系电话',
            id: '77329844',
          },
          {
            title: '客户经理征信等级',
            key: 'custManagerCreditRate',
            dataIndex: 'custManagerCreditRate',
            label: '客户经理征信等级',
            id: '3562793',
          },
          {
            title: '已申请红名单数（个）',
            key: 'appliedRedListNum',
            dataIndex: 'appliedRedListNum',
            label: '已申请红名单数（个）',
            id: '0413365',
          },
          {
            title: '红名管控上线数（个）',
            key: 'redControlNum',
            dataIndex: 'redControlNum',
            label: '红名管控上线数（个）',
            id: '137417',
          },
          {
            title: '当年红名单已申请次数（次）',
            key: 'appliedRedListNumYear',
            dataIndex: 'appliedRedListNumYear',
            label: '当年红名单已申请次数（次）',
            id: '256653',
          },
          {
            title: '集团最早欠费时间',
            key: 'groupEarliestOverdueTime',
            dataIndex: 'groupEarliestOverdueTime',
            label: '集团最早欠费时间',
            id: '872497',
          },
          {
            title: '集团总欠费（元）',
            key: 'groupTotalOverdueFee',
            dataIndex: 'groupTotalOverdueFee',
            label: '集团总欠费（元）',
            id: '1918254',
          },
          {
            title: '已申请白名单次数（次）',
            key: 'appliedWhiteListNum',
            dataIndex: 'appliedWhiteListNum',
            label: '已申请白名单次数（次）',
            id: '533072',
          },
          {
            title: '最大逾期月数 （月）',
            key: 'maxOverdueMonth',
            dataIndex: 'maxOverdueMonth',
            label: '最大逾期月数 （月）',
            id: '40659',
          },
          {
            title: '集团累计逾期（元）',
            key: 'groupCumulativeOverdueFee',
            dataIndex: 'groupCumulativeOverdueFee',
            label: '集团累计逾期（元）',
            id: '5515184',
          },
          {
            title: '已申请白名单天数（天）',
            key: 'appliedWhiteListDay',
            dataIndex: 'appliedWhiteListDay',
            label: '已申请白名单天数（天）',
            id: '999316',
          },
          {
            title: '最近一次催缴要求（近一年）',
            key: 'lastCollectionRequireYear',
            dataIndex: 'lastCollectionRequireYear',
            label: '最近一次催缴要求（近一年）',
            id: '578491',
          },
          {
            title: '最近一次催缴时间（近一年）',
            key: 'lastCollectionTimeYear',
            dataIndex: 'lastCollectionTimeYear',
            label: '最近一次催缴时间（近一年）',
            id: '88838',
          },
          {
            title: '最近一次催缴动作（近一年）',
            key: 'lastCollectionActionYear',
            dataIndex: 'lastCollectionActionYear',
            label: '最近一次催缴动作（近一年）',
            id: '3671033',
          },
        ]}
        dataSource={data?.groupInfo}
        labelSize={'200px'}
        $$componentItem={{
          id: 'Description_6008979',
          uid: 'Description_6008979',
          type: 'Description',
          ...componentItem,
        }}
        disabled={false}
        visible={true}
        readOnly={false}
        ref={(r: any) => refs.setComponentRef(r, 'Description_6008979')}
        {...injectData}
      />
    </div>
  );
};

export default withPageHOC(BusiComp963983$$BusiComp, {
  pageId,
  hasLogin: true,
  dataSource,
  defaultState: { groupInfo: '' },
});
